### ISSUE TITLE
Sdk is not working in release Build Gradle version: 3.4.1

### ISSUE THREAD

**Issue by sh-soltanpour** [metrixorg/MetrixSDK-AndroidSample#1]
Hi, 
when I'm testing my app using your SDK in development mode, it works fine and data is shown in Metrix dashboard. 
But in release mode, it's not working; I can't see any related data in the dashboard.
Build Tools Version: 28.0.3, Build Gradle version: 3.4.1.

**Comment by miladheydari** [comment]
For build gradle 3.4 and later versions, R8 is enabled by default, so the Metrix proguard should be changed as follows:
```
#Metrix
-keep class ir.metrix.sdk.** { *; }

#referral
-keep public class com.android.installreferrer.** { *; }

#gms
-keep class com.google.android.gms.** { *; }

-dontwarn android.content.pm.PackageInfo
```
