### ISSUE TITLE
آیا کتابخانه شما شناسه تبلیغاتی گوگل را دریافت میکند؟

### ISSUE THREAD

**Issue by msddev** [metrixorg/MetrixSDK-AndroidSample#2]
من کتابخانه متریکس را به اپلیکیشن خودم اضافه کردم و بعد از انتشار نسخه در استور گوگل پلی، با اخطار **نقض قوانین گوگل پلی** به دلیل جمع آوری شناسه تبلیغاتی گوگل مواجه شدم. 
راه حل این مشکل چیست؟

**Comment by miladheydari** [comment]
سلام 
اگه شما کتابخونه مارو به صورت کامل پیاده سازی کرده باشید، ما شناسه تبلیغاتی گوگل دریافت میکنیم.
شما در صفحه قوانین که به گوگل پلی ارائه میدید باید به این موضوع اشاره کرده باشید.

**Comment by msddev** [comment]
ما هنوز در مرحله توسعه هستیم و صفحه قوانین آماده نشده است. راه حل شما چیست؟
